apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: sovernut/kub-data-demo:1
          volumeMounts:
            - mountPath: /app/story # defined in Dockerfile
              name: story-volume
      volumes:
        - name: story-volume
          hostPath:
            path: /data # share file in NodeWorker
            type: DirectoryOrCreate # create if not exists
  
