apiVersion: v1
kind: PersistentVolume # detach from node
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem # has directory use this !
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # only mode make sense for hostPath
  hostPath:
    path: /data # share file in NodeWorker
    type: DirectoryOrCreate # create if not exists
