apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce # only mode make sense for hostPath
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
          
  
